import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getAllRecipes } from '../lib/recipes';

export default function Home({ data }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next App - Recipes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>Brandon Recipes</h1>
                <ul className={styles.grid}>
                    {data.allRecipes.map((recipe) => (
                        <li key={recipe.id} className={styles.card}>
                            <Link href={`/recipes/${recipe.id}`}>
                                <a>
                                    <Image
                                        className={styles.recipe__photo}
                                        src={recipe.acf.recipe_photo.url}
                                        height={recipe.acf.recipe_photo.height}
                                        width={recipe.acf.recipe_photo.width}
                                        alt=""
                                    />
                                    <h3>{`${recipe.title.rendered.substring(0, 18)}`}</h3>
                                    <ul className={styles.info}>
                                        <li className={styles.info__item}>
                                            <p>
                                                Tür: <strong>{recipe.acf.recipe_type}</strong>
                                            </p>
                                        </li>
                                        <li className={styles.info__item}>
                                            <p>
                                                Tat: <strong>{recipe.acf.recipe_flavor}</strong>
                                            </p>
                                        </li>
                                        <li className={styles.info__item}>
                                            <p>
                                                Zaman: <strong>{recipe.acf.recipe_time}</strong>
                                            </p>
                                        </li>
                                        <li className={styles.info__item}>
                                            <p>
                                                Seviye:{' '}
                                                <strong>{recipe.acf.recipe_difficulty}</strong>
                                            </p>
                                        </li>
                                    </ul>
                                </a>
                            </Link>
                        </li>
                    ))}
                </ul>
            </main>
            <footer className={styles.footer}>eee</footer>
        </div>
    );
}

export async function getStaticProps() {
    const data = await getAllRecipes();

    return {
        props: {
            data,
        },
    };
}
